tag-template: "b3p-gt2-modules-$NEXT_MINOR_VERSION"
name-template: v$NEXT_MINOR_VERSION 🎁

version-template: "$MAJOR.$MINOR"

template: |
  ## Aanpassingen
  $CHANGES

categories:
  - title: 🚀 Nieuwe features en verbeteringen
    labels:
      - enhancement
      - feature
  - title: 🐛 Bug Fixes
    labels:
      - bug
      - fix
      - bugfix
      - regression
  - title: Beveiligings updates en Fixes
    labels:
      - security
  - title: 📖 Documentatie updates
    label: documentation
  - title: 🚨 Verwijderd
    label: removed
  - title: ⚠️ Deprecated
    label: deprecated
  - title: 🚦 Testcases
    labels:
      - tests
      - test
  - title: 🔨 Klussen
    labels:
      - task
      - chore
  - title: 🔨 Dependency updates
    label: dependencies

replacers:
  - search: '/CVE-(\d{4})-(\d+)/g'
    replace: 'https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-$1-$2'
